	<p style="margin-left:25px;"><font face="arial" size="2"><strong>Detalhes do cartão:</strong></font></p>
	<p style="padding:10px; margin:0 25px; margin-bottom:10px; background:#f4f4f4;">	
		<font face="arial" size="2">Cartão: $!creditCardBrand</font><br />
		<font face="arial" size="2">N&deg; do Cartão: $!creditCardNumber</font><br />
		<font face="arial" size="2">Validade: <font face="arial" size="+1" color="#FF0000"><b>$!expiringDate</b></font></font><br />
	</p>
