	<tr><!-- rodape:inicio -->
		<td>
			<font face="arial" size="-1">
				<br>Atenciosamente,<br/>Equipe PagSeguro.<br/><br/>
				<strong>PagSeguro</strong> - A forma mais fácil e segura de vender através da internet.
			</font>
		</td>
	</tr>
	<tr>
		<td align="center">
			<hr size="2" color="#EFEFEF">
			<font face="arial" size="-1">
			DÚVIDAS? Acesse #set($url1='http://www.pagseguro.com.br/atendimento')
			<a href="${url1}">${url1}</a>
			</font>
		</td>
	</tr>
	<tr>
		<td align="left">
			<hr size="-2" color="#EFEFEF">
			<font face="arial" size="-2" color="gray">Este é um e-mail automático disparado pelo sistema. Favor não respondê-lo, pois esta conta não é monitorada.<br/><br/>O PagSeguro não solicita os seus dados cadastrais ou a sua senha por e-mail.<br/><br/>Veja as <a style='font-size:10px; color:#0000FF' href="https://sac.uol.com.br/info/protecao_privacidade/normas_protecao_privacidade.jhtm">Normas de Segurança e Privacidade</a> e as <a style='font-size:10px; color:#0000FF' href="https://pagseguro.uol.com.br/regras-de-uso.jhtml">Regras de Uso do PagSeguro</a>.<br/><br/></font>
		</td>
	</tr>
	<tr>
		<td background="https://p.simg.uol.com.br/out/pagseguro/i/email/deg_rodapemail.gif">&nbsp;</td>
	</tr><!-- rodape:fim -->
